spring:
  application:
    name: golden-raspberry-awards
  jpa:
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB